### ISSUE TITLE
How are OW functions deployed with chaining?

### ISSUE THREAD

**Issue by kingzevin** [CAPS-Cloud/IoT-Platform-Migration#1]
Hello authors, 
Thanks for your great work to be shown in WoSC. I'm reading your code to learn. And I'm wondering how you chained the authentication function with other functions on OpenWhisk. I've tried to find the answer in this repository but failed. It would be really appreciated if you can tell me when you're available. 
Thanks!

**Comment by kky-fury** [comment]
Hi kingzevin,

You can create action sequences in OpenWhisk as described here (action sequences): https://github.com/apache/openwhisk/blob/master/docs/actions.md

**Comment by kingzevin** [comment]
Hi kky-fury,

Thanks for your reply!
I know how to create action sequences but I'm wondering whether your actions in the repository can be chained via an action sequence. For example, I'm wondering how the authentication action cooperate with different middleware functions, since the result of the authentication action seems like an http response. Or did you check this result in your sequence, or composition, before passing the request message to the subsequent middleware functions? 

Thanks again!

**Comment by victorpacyna** [comment]
Hi kingzevin,
this [blog post](http://jamesthom.as/2019/02/openwhisk-web-action-errors-with-sequences/) explains it quite well. The main idea is to return an error response in the ow action, that is used as the middleware. OW then interrupts the sequence and returns at that point already. I hope this answers your questions, otherwise feel free to reach out again. Best regards!

**Comment by kingzevin** [comment]
Hi Victor,

Thanks for your instant reply! The blog post you've mentioned answered my question. 
Sorry to bother, but then I guess the current code in functions/OW-Functions-All/AuthenticationApp cannot be directly used in the action sequence? The post says when the authentication passes, it should return the original params, instead of a new http response. And I guess the http response cannot be accepted as the parameter by the subsequent functions like UserControllerAdd?
Thanks again for your kind answer. I appreciate it so much.

**Comment by victorpacyna** [comment]
Please have a look at this code: functions/OW-Functions/AuthenticationNew/app.js. You will find the parameters passed through in the successful/200 response. Best regards!

**Comment by kingzevin** [comment]
Oooh!
I got it! I only checked OW-Functions-All. 
Thanks a lot!

**Comment by kingzevin** [comment]
Thanks to both of you!
