### ISSUE TITLE
About Decomposing the IoTCore Service into 30+ Individual Functions

### ISSUE THREAD

**Issue by kingzevin** [CAPS-Cloud/IoT-Platform-Migration#2]
Hi authors,

It's me again. In the paper, you decomposed the IoTCore service into more than 30 individual functions based on the endpoints. My question is that, have you done some evaluations to compare the version of decomposing versus the original huge one? I agree that smaller pieces of code involve less libraries and thus may give a better performance. I'm just curious that have you testified that with some evaluation?

Thanks!

**Comment by kky-fury** [comment]
HI @kingzevin,

This is a really good question. We are currently investigating this. What I can currently say is that fine-grained decomposition in most cases leads to worse performance and more costs on public FaaS platforms.

Btw, are you one of the authors of the APSys'21 paper: https://dl.acm.org/doi/10.1145/3476886.3477510?

**Comment by kingzevin** [comment]
Hi @kky-fury, 

Yes, I'm the first author of that paper. Thanks for your answer. It's a fancy observation. I'm also interested in the problem. Haha.

**Comment by kingzevin** [comment]
Hi @kky-fury ,

Sorry to bother again. I'm wondering by fine-grained decomposition, do you mean the chaining functions? Or do you also think the decomposition based on the endpoints, i.e., to dispatch one endpoint to one fine-grained function, will cause the worse performance? I think my previous question may be not so clear. In my intuition, if no chaining is involved, the fine-grained function should have some better performance for the less resource consumption and the less code to load. 
I'm curious about your thoughts about the cause of the worse performance with decomposition. 
Thanks!

**Comment by kky-fury** [comment]
Hi @kingzevin,

I really liked your paper. It was very well written.

Yes, chaining in most cases leads to worse performance. But also decomposing a large service into individual functions in most cases will lead to worse performance and higher costs. We evaluated this on GCR.

**Comment by kingzevin** [comment]
Hi @kky-fury ,

Haha, I got it.
Hope to see your new paper!
